export default data = [
  {
    employer_name: 'Dice',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0',
    employer_website: null,
    employer_company_type: 'Information',
    job_publisher: 'LinkedIn',
    job_id: 'lLDL3hNGc6wAAAAAAAAAAA==',
    job_employment_type: 'CONTRACTOR',
    job_title: 'Full Stack React Developer / Node Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/full-stack-react-developer-node-developer-at-dice-3550411783',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5805,
    job_description:
      "Title : Full Stack React Developer / Node Developer\n\nClient : Goose head Insurance\n\nLocation : Hybrid 3days onsite per week - 1500 Solana Blvd Bldg 4, Westlake, TX, 76262-1690, USA\n\nDuration : 12+ Months Contract\n\nTop Skills' Details\n• 5+ years of experience as a Full Stack Software Engineer\n• Reacts.js\n• Node.js\n• Postgres DB or equivalent\n\nHybrid schedule - Mon, Tues and Thurs\n\nSecondary Skills - Nice To Haves\n• React\n• SQL\n• MySQL\n• PostgreSQL\n\nJob Description\n• Bachelor's or Master's degree in Computer Science or a related field.\n• 5+ years of experience as a Full Stack Software Engineer with React.js and Node.js (required)\n• Languages: JavaScript, TypeScript, HTML, CSS, Java\n• Databases: SQL, PostgreSQL\n• Solid understanding of software development principles, design patterns, and best practices.\n• Solid knowledge of React and Redux principles.\n• Experience with CI/CD, Source Control such as Git.\n• Experience with unit testing, release procedures, coding design, and documentation protocol as well as change management procedures.\n• Ability to manage tasks independently and take ownership of responsibilities.\n• Ability to learn from mistakes and apply constructive feedback to improve performance.\n• Must demonstrate initiative and effective independent decision-making skills.\n• Ability to adapt to a rapidly changing environment.\n• In-depth understanding of the software development life cycle.\n• Experience with iPaaS, Salesforce Apex, Styled-components, Heroku, Heroku-connect (Preferred)\n• Proficiency in state management systems like: Flux, Redux.\n• Demonstrated organizational, analytical, and interpersonal skills.\n• Excellent communication and problem-solving skills.\n\nAdditional Skills & Qualifications\n• Design, develop, and maintain software applications using React, Node.js, and Postgres DB\n• Develop high-quality, scalable, clean, and maintainable code.\n• Collaborate with Product Owners, Business Analysts, Designers, and other Engineers to define project requirements, write code and ensure successful delivery.\n• Debug and troubleshoot issues as they arise and provide a timely resolution.\n• Contribute to the development of best practices and coding standards.\n• Contribute to the architecture of our applications.\n• Contribute to the design of an efficient, reliable, and effective database.\n• Create technical design documentation.\n• Make design/coding decisions keeping the customer experience at the forefront.\n• Provide mentorship and guidance to junior team members.\n• Participate in code reviews, and guidance on engineering best practices and compliance with development procedures.\n• Accountable for ensuring all aspects of product development follow compliance and security best practices.\n• Anticipate and communicates blockers and delays before they require escalation.\n\nEmployee Value Proposition (EVP)\n\nGrowing 25m to 250m in the last 5 years\n\nProduct Dev group is focused on integrating the get quote and buy policy functionality.\n\nThey have 140 Insurance carriers they work with... currently you can go on their site and get a quote but you ultimately have to then get on the phone with an agent. This team in working on integrating with their carriers so you can get a quote and buy a policy all from the site instead of talking to an agent.\n\nThink or the or Travelocity for insurance.\n\nWork Environment\n\nHybrid schedule - Mon, Tues and Thurs\n\nVery collaborative team\n\nCurrent they have two scrum teams and are building out a third\n\nBusiness Drivers/Customer Impact\n\nProduct Dev group is focused on integrating the get quote and buy policy functionality.\n\nThey have 140 Insurance carriers they work with... currently you can go on their site and get a quote but you ultimately have to then get on the phone with an agent. This team in working on integrating with their carriers so you can get a quote and buy a policy all from the site instead of talking to an agent.\n\nThink or the or Travelocity for insurance.\n\nWhy is the position open(provide details)\n\nBuild a new scrum team\n\nExternal Communities Job Description\n\nDesign, develop, and maintain software applications using React, Node.js, and Postgres DB\n• Develop high-quality, scalable, clean, and maintainable code.\n• Collaborate with Product Owners, Business Analysts, Designers, and other Engineers to define project requirements, write code and ensure successful delivery.\n• Debug and troubleshoot issues as they arise and provide a timely resolution.\n• Contribute to the development of best practices and coding standards.\n• Contribute to the architecture of",
    job_is_remote: false,
    job_posted_at_timestamp: 1680231450,
    job_posted_at_datetime_utc: '2023-03-31T02:57:30.000Z',
    job_city: 'Westlake',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.991234,
    job_longitude: -97.195015,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=lLDL3hNGc6wAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-04-30T02:57:30.000Z',
    job_offer_expiration_timestamp: 1682823450,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Reacts.js',
        'Postgres DB or equivalent',
        'MySQL',
        "Bachelor's or Master's degree in Computer Science or a related field",
        '5+ years of experience as a Full Stack Software Engineer with React.js and Node.js (required)',
        'Languages: JavaScript, TypeScript, HTML, CSS, Java',
        'Solid understanding of software development principles, design patterns, and best practices',
        'Solid knowledge of React and Redux principles',
        'Experience with unit testing, release procedures, coding design, and documentation protocol as well as change management procedures',
        'Ability to learn from mistakes and apply constructive feedback to improve performance',
        'Must demonstrate initiative and effective independent decision-making skills',
        'Proficiency in state management systems like: Flux, Redux',
        'Demonstrated organizational, analytical, and interpersonal skills',
        'Excellent communication and problem-solving skills',
        'Design, develop, and maintain software applications using React, Node.js, and Postgres DB',
        'Anticipate and communicates blockers and delays before they require escalation',
      ],
      Responsibilities: [
        'Ability to manage tasks independently and take ownership of responsibilities',
        'Collaborate with Product Owners, Business Analysts, Designers, and other Engineers to define project requirements, write code and ensure successful delivery',
        'Debug and troubleshoot issues as they arise and provide a timely resolution',
        'Contribute to the development of best practices and coding standards',
        'Contribute to the architecture of our applications',
        'Contribute to the design of an efficient, reliable, and effective database',
        'Create technical design documentation',
        'Make design/coding decisions keeping the customer experience at the forefront',
        'Provide mentorship and guidance to junior team members',
        'Participate in code reviews, and guidance on engineering best practices and compliance with development procedures',
      ],
      Benefits: [
        'This team in working on integrating with their carriers so you can get a quote and buy a policy all from the site instead of talking to an agent',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Peyton Resource Group',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUBhZYOjdHIaY0vuyanuHMtfVydg-ydCkKL4XX&s=0',
    employer_website: null,
    employer_company_type: 'Staffing',
    job_publisher: 'LinkedIn',
    job_id: '2vYzEuPJ-f0AAAAAAAAAAA==',
    job_employment_type: 'FULLTIME',
    job_title: 'React Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/react-developer-at-peyton-resource-group-3541963551',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5743,
    job_description:
      'The React Developer position is for an experienced ReactJS software developer to support web and mobile web application development. The successful candidate will perform system analysis and develop advanced programming code in addition to providing support and problem resolution for computer applications.\n\nThe Role:\n• Analyze, design, and develop software that delivers clean, maintainable code within a large, highly complex, existing code base with a focus on front-end UI that is tightly coupled to data\n• Develop web and mobile web software solutions solutions written in Typescript with a heavy focus on database and ReactJS frameworks\n• Designs, codes, and debugs applications in various software languages\n• Completes software analysis, code analysis, requirements analysis, software reviews, identification of code metrics, system risk analysis, and software reliability analysis\n• Assist with end user training, documentation, and support\n• Analyzes system specifications and translates system requirements to task specifications independently or in collaboration with other team members\n\nOur Ideal Candidate:\n• A Bachelor’s degree in computer science, information systems, or a related field (required)\n• Three or more years of professional software development experience with React, TypeScript, Redux, and supporting technologies is required\n• Strong object-oriented design and coding ability, including experience with object-oriented languages: Java, C#, C++, PHP is a plus\n• Experience with backend web application development (Spring, Tomcat) and relational databases (SQL Server, PostgreSQL, etc.) is a plus\n• Experience with other web-based, front-end technologies such as Angular and EXTJS is a plus\n• An understanding of modern software development techniques, including the full SDLC, object-oriented design, continuous integration, revision control systems (Git preferred), and agile methodologies\n\nWhat we can offer you:\n\n· Competitive pay\n\n· 7% Employer-Funded retirement contribution starting day one\n\n· Full insurance benefits\n\n· Holidays, PTO and a paid week off in the last week of December\n\nThis position is located in San Antonio, TX with a hybrid work schedule of 3 days remote/2 days on campus after training.',
    job_is_remote: false,
    job_posted_at_timestamp: 1680117991,
    job_posted_at_datetime_utc: '2023-03-29T19:26:31.000Z',
    job_city: 'San Antonio',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 29.42519,
    job_longitude: -98.49459,
    job_benefits: ['paid_time_off', 'health_insurance', 'retirement_savings'],
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=2vYzEuPJ-f0AAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-04-28T19:26:31.000Z',
    job_offer_expiration_timestamp: 1682709991,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 85000,
    job_max_salary: 105000,
    job_salary_currency: 'USD',
    job_salary_period: 'YEAR',
    job_highlights: {
      Qualifications: [
        'A Bachelor’s degree in computer science, information systems, or a related field (required)',
        'Three or more years of professional software development experience with React, TypeScript, Redux, and supporting technologies is required',
      ],
      Responsibilities: [
        'The successful candidate will perform system analysis and develop advanced programming code in addition to providing support and problem resolution for computer applications',
        'Analyze, design, and develop software that delivers clean, maintainable code within a large, highly complex, existing code base with a focus on front-end UI that is tightly coupled to data',
        'Develop web and mobile web software solutions solutions written in Typescript with a heavy focus on database and ReactJS frameworks',
        'Designs, codes, and debugs applications in various software languages',
        'Completes software analysis, code analysis, requirements analysis, software reviews, identification of code metrics, system risk analysis, and software reliability analysis',
        'Assist with end user training, documentation, and support',
        'Analyzes system specifications and translates system requirements to task specifications independently or in collaboration with other team members',
      ],
      Benefits: [
        'Competitive pay',
        '7% Employer-Funded retirement contribution starting day one',
        'Full insurance benefits',
        'Holidays, PTO and a paid week off in the last week of December',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Talent Group',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRK45P-8ndJb_JYX9FL79Ht8eyfOk_Xc3ZLIqj&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'Glassdoor',
    job_id: 'NZlzCVxKVCEAAAAAAAAAAA==',
    job_employment_type: 'FULLTIME',
    job_title: 'React Developer',
    job_apply_link:
      'https://www.glassdoor.com/job-listing/react-developer-talent-group-JV_IC1139761_KO0,15_KE16,28.htm?jl=1008560631203',
    job_apply_is_direct: true,
    job_apply_quality_score: 0.5596,
    job_description:
      '• Experince in JavaScript or TypeScript, HTML 5, CSS 3, Web Development frameworks like React - Redux, along with Bootstrap customisation or material UI\n• Strong knowledge on react-redux data flow concepts along with middleware like redux-saga or react-thunk.\n• Need Strong knowledge in React Functional components with hooks concepts.\n• Strong in JavaScript concepts like ES5 and ES6.\n\nJob Type: Full-time\n\nSalary: Up to $120,000.00 per year\n\nBenefits:\n• 401(k)\n\nExperience level:\n• 5 years\n\nSchedule:\n• 8 hour shift\n\nWork Location: One location',
    job_is_remote: false,
    job_posted_at_timestamp: 1680220800,
    job_posted_at_datetime_utc: '2023-03-31T00:00:00.000Z',
    job_city: 'Austin',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: ['retirement_savings'],
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=NZlzCVxKVCEAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-04-30T00:00:00.000Z',
    job_offer_expiration_timestamp: 1682812800,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 120000,
    job_max_salary: 120000,
    job_salary_currency: 'USD',
    job_salary_period: 'YEAR',
    job_highlights: {
      Qualifications: [
        'Experince in JavaScript or TypeScript, HTML 5, CSS 3, Web Development frameworks like React - Redux, along with Bootstrap customisation or material UI',
        'Strong knowledge on react-redux data flow concepts along with middleware like redux-saga or react-thunk',
        'Need Strong knowledge in React Functional components with hooks concepts',
        '5 years',
      ],
      Benefits: [
        'Salary: Up to $120,000.00 per year',
        '401(k)',
        '8 hour shift',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Axelon Services Corporation',
    employer_logo:
      'https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=330304200380493',
    employer_website: 'http://www.axelon.com',
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_id: 'ul_pD_5bazEAAAAAAAAAAA==',
    job_employment_type: 'CONTRACTOR',
    job_title: 'Java/ React Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/java-react%C2%A0developer-at-axelon-services-corporation-3544857796',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5772,
    job_description:
      'Global Financial Firm located in IRVING, TX has an immediate contract opportunity for an experienced Java/ React Developer\n\n"This role is currently on a Hybrid Schedule.\nYou will need to have reliable internet, computer and android or iphone for remote access into the client systems during remote work.\nWe will be expected in the office weekly 1-3 days depending on the team requirement.\n• ***Video/ f2f interviews are required prior to all offers.\n\nReact/Java\nClient Commercial Bank (CCB) provides the highest quality financial advice, helping business like yours prosper and grow in domestic markets, as well as internationally. CCB Technology is seeking a strong developer to work on key business products and client initiatives.\n\nResponsibilities of this role is building frontend of the applications, and developing the REST APIs and supporting the apps. As an application developer, candidate is expected to have good analytical thinking, problem solving, good programming/technical fundamentals and eagerness to learn new technologies/concepts. Candidate must be open to accept challenges and suggestions.\n\nBackend (Required):\n1. Experience in developing low latency and high throughput APIs using Spring Boot.\n2. Strong Core Java and functional programming experience.\n3. Strong experience in data modeling and experience with relational and no-sql database, Oracle and MongoDB.\n4. Understanding of integrating APIs with third party libraries/vendors and handle the security around it.\n5. Responsible for server side design & development.\n6. Development of common, reusable components and services.\n7. Ability to take initiative to research, learn and recommend emerging technologies.\n8. Ability to work with global teams and lead them on critical project initiatives.\n9. Responsible for peer code reviews, unit testing, leveraging CICD pipeline of an application.\n\nFrontend (Required):\n1. Experience working as a React developer\n2. Solid knowledge of JavaScript, CSS, HTML, and front-end languages including Node JS.\n3. Knowledge of React tools including React.js, Hooks, Context, Web pack, Bootstrap, SASS, Express, Redux, and Flux.\n4. Have thorough knowledge of E2E deployment of an UI application.\n5. Developing and implementing highly-responsive user interface components using React concepts.\n6. Reviewing application requirements and interface designs.\n7. Proficiency with browser based debugging and performance testing.\n\nOther areas (Required):\n1. Experience using Git/BitBucket.\n2. Good communication skills, both written and verbal.\n3. Unix shell scripting.\n4. Good troubleshooting skills.\n\nGood to have (Optional):\n1. Knowledge of Couchbase, ElasticSearch, and GraphQL.\n2. Knowledge of OpenShift Container Platform.\n3. Knowledge of Hazelcast.\n4. Java memory management.\n5. Winston logger framework for Node-Js.\n6. Prior experience with building distributed, multi-tier applications is highly desirable.\n7. Experience with building apps which are highly performant and scalable will be great.\n8. Experience building accessible digital experiences complying to AODA/WCAG/ADA and knowledge of using web accessibility tools such as NVDA/JAWS/AXE.',
    job_is_remote: false,
    job_posted_at_timestamp: 1680280223,
    job_posted_at_datetime_utc: '2023-03-31T16:30:23.000Z',
    job_city: 'Irving',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.81402,
    job_longitude: -96.94889,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ul_pD_5bazEAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-09-27T17:24:36.000Z',
    job_offer_expiration_timestamp: 1695835476,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        '***Video/ f2f interviews are required prior to all offers',
        'As an application developer, candidate is expected to have good analytical thinking, problem solving, good programming/technical fundamentals and eagerness to learn new technologies/concepts',
        'Candidate must be open to accept challenges and suggestions',
        'Experience in developing low latency and high throughput APIs using Spring Boot',
        'Strong Core Java and functional programming experience',
        'Strong experience in data modeling and experience with relational and no-sql database, Oracle and MongoDB',
        'Understanding of integrating APIs with third party libraries/vendors and handle the security around it',
        'Responsible for server side design & development',
        'Development of common, reusable components and services',
        'Experience working as a React developer',
        'Solid knowledge of JavaScript, CSS, HTML, and front-end languages including Node JS',
        'Knowledge of React tools including React.js, Hooks, Context, Web pack, Bootstrap, SASS, Express, Redux, and Flux',
        'Have thorough knowledge of E2E deployment of an UI application',
        'Developing and implementing highly-responsive user interface components using React concepts',
        'Reviewing application requirements and interface designs',
        'Proficiency with browser based debugging and performance testing',
        'Experience using Git/BitBucket',
        'Good communication skills, both written and verbal',
        'Unix shell scripting',
        'Good troubleshooting skills',
        'Knowledge of Couchbase, ElasticSearch, and GraphQL',
        'Knowledge of OpenShift Container Platform',
        'Java memory management',
        'Winston logger framework for Node-Js',
        'Experience with building apps which are highly performant and scalable will be great',
        'Experience building accessible digital experiences complying to AODA/WCAG/ADA and knowledge of using web accessibility tools such as NVDA/JAWS/AXE',
      ],
      Responsibilities: [
        'You will need to have reliable internet, computer and android or iphone for remote access into the client systems during remote work',
        'We will be expected in the office weekly 1-3 days depending on the team requirement',
        'Responsibilities of this role is building frontend of the applications, and developing the REST APIs and supporting the apps',
        'Ability to take initiative to research, learn and recommend emerging technologies',
        'Ability to work with global teams and lead them on critical project initiatives',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Texas Biomedical Research Institute',
    employer_logo:
      'https://www.uthscsa.edu/sites/default/files/2018/texas_biomed.png',
    employer_website: 'https://www.txbiomed.org',
    employer_company_type: 'Research',
    job_publisher: 'ZipRecruiter',
    job_id: 'iWctWpwxOLoAAAAAAAAAAA==',
    job_employment_type: 'FULLTIME',
    job_title: 'React Developer',
    job_apply_link:
      'https://www.ziprecruiter.com/c/Texas-Biomedical-Research-Institute/Job/React-Developer/-in-San-Antonio,TX?jid=fb3576b05306cc0c',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6661,
    job_description:
      "The React Developer position is for an experienced ReactJS software developer tosupport web and mobile web application development. The successful candidatewill perform system analysis and develop advanced programming code in additionto providing support and problem resolution for computer applications.\n\nThe Role:\nAnalyze, design, and develop software that delivers clean, maintainable code within a large, highly complex, existing code base with a focus on front-end UI that is tightly coupled to data\nDevelop web and mobile web software solutions solutions written in Typescript with a heavy focus on database and ReactJS frameworks\nDesigns, codes, and debugs applications in various software languages\nCompletes software analysis, code analysis, requirements analysis, software reviews, identification of code metrics, system risk analysis, and software reliability analysis\nAssist with end user training, documentation, and support\nAnalyzes system specifications and translates system requirements to task specifications independently or in collaboration with other team members\n\nOurIdeal Candidate:\nA Bachelor's degree in computer science, information systems, or a related field (required)\nThree or more years of professional software development experience with React, TypeScript, Redux, and supporting technologies is required\nStrong object-oriented design and coding ability, including experience with object-oriented languages: Java, C#, C++, PHP is a plus\nExperience with backend web application development (Spring, Tomcat) and relational databases (SQL Server, PostgreSQL, etc.) is a plus\nExperience with other web-based, front-end technologies such as Angular and EXTJS is a plus\nAn understanding of modern software development techniques, including the full SDLC, object-oriented design, continuous integration, revision control systems (Git preferred), and agile methodologies\n\nWho We Are:\nTexas Biomedical Research Institute is one of the world'sleading independent biomedical research institutions dedicated toadvancing global human health through innovative biomedical research. TexasBiomed aims to unravel the mysteries of infectious diseases through innovativethinking, creative problem solving and cutting edge technologies.\n\nWhat we can offer you:\n• Competitive pay\n• 7% Employer-Funded retirement contributionstarting day one\n• Full insurance benefits\n• Holidays, PTO and a paid week off in the last week of December\n\nThis position is located in San Antonio, TX with a hybrid work schedule of 3 days remote/2 days on campus after training.\n• *All new hiresmust present proof of an up to date COVID-19 immunization record to includebooster(s) if eligible.",
    job_is_remote: false,
    job_posted_at_timestamp: 1668470400,
    job_posted_at_datetime_utc: '2022-11-15T00:00:00.000Z',
    job_city: 'San Antonio',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 29.42519,
    job_longitude: -98.49459,
    job_benefits: ['paid_time_off', 'health_insurance', 'retirement_savings'],
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=iWctWpwxOLoAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-04-30T00:00:00.000Z',
    job_offer_expiration_timestamp: 1682812800,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "A Bachelor's degree in computer science, information systems, or a related field (required)",
        'Three or more years of professional software development experience with React, TypeScript, Redux, and supporting technologies is required',
      ],
      Responsibilities: [
        'The successful candidatewill perform system analysis and develop advanced programming code in additionto providing support and problem resolution for computer applications',
        'Analyze, design, and develop software that delivers clean, maintainable code within a large, highly complex, existing code base with a focus on front-end UI that is tightly coupled to data',
        'Develop web and mobile web software solutions solutions written in Typescript with a heavy focus on database and ReactJS frameworks',
        'Completes software analysis, code analysis, requirements analysis, software reviews, identification of code metrics, system risk analysis, and software reliability analysis',
        'Assist with end user training, documentation, and support',
        'Analyzes system specifications and translates system requirements to task specifications independently or in collaboration with other team members',
      ],
      Benefits: [
        'Competitive pay',
        '7% Employer-Funded retirement contributionstarting day one',
        'Full insurance benefits',
        'Holidays, PTO and a paid week off in the last week of December',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Intellisoft Technologies',
    employer_logo:
      'https://www.intellisofttech.com/wp-content/themes/intellisoft/images/logo.png',
    employer_website: 'http://www.intellisofttech.com',
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_id: '41HSxPWKncEAAAAAAAAAAA==',
    job_employment_type: 'CONTRACTOR',
    job_title: 'react developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/react-developer-at-intellisoft-technologies-3541985185',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5759,
    job_description:
      'Hello\n\nJob Title: React Front-End Developer/ .Net/ C#\nLocation: Austin, TX (Hybrid)\nDuration: Contract on w2\n\nJob Description:\nStrong experience in React with some C#/.net.\nBrand new team building a Greenfield financial application. Backend is C#/.net, but they do not need any backend experience.\n\nYours Cordially\nHimanshu Sharma (Team Recruitment- US Professional Services)\nIntellisoft Technologies Inc.\nPhone: 972 756 1212 Ext.161\n1320 Greenway Drive STE 460 Irving TX 75038\nhimanshu@intellisofttech.com | www.intellisofttech.com\n(A DFWMSDC, NCTRA Minority and Texas HUB certified Firm)\nOracle Gold Partner & Client Software Partner',
    job_is_remote: false,
    job_posted_at_timestamp: 1680122510,
    job_posted_at_datetime_utc: '2023-03-29T20:41:50.000Z',
    job_city: 'Dallas',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=41HSxPWKncEAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-09-25T20:41:53.000Z',
    job_offer_expiration_timestamp: 1695674513,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Strong experience in React with some C#/.net',
        'Backend is C#/.net, but they do not need any backend experience',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Vastika Inc.',
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'Salary.com',
    job_id: '8EiWeZemhJ8AAAAAAAAAAA==',
    job_employment_type: 'FULLTIME',
    job_title: 'React Developer',
    job_apply_link:
      'https://www.salary.com/job/vastika-inc/react-developer/j202303290134153247189',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5626,
    job_description:
      'Job Description\n\nNote: Onsite role.\n\nDescription:\n• Bachelor’s Degree in Computer Science or related field\n• A minimum of 5 years of experience in software design and development\n• Deep understanding of Computer Science fundamentals\n• Strong development, debugging and troubleshooting skills\n• Excellent written, verbal communication skills. Able to work in teams and collaborative fashion.\n\nLanguages/Technologies:\n• React / React Native / Node.js using JavaScript / TypeScript\n• Bitbucket/JIRA/GIT Workflow\n\nOperating Systems:\n• Linux\n• Windows\n\nReport this job\n• Dice Id: 10305143\n• Position Id: 7830062\n•',
    job_is_remote: false,
    job_posted_at_timestamp: 1680134400,
    job_posted_at_datetime_utc: '2023-03-30T00:00:00.000Z',
    job_city: 'Irving',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.81402,
    job_longitude: -96.94889,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=8EiWeZemhJ8AAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-09-29T00:00:00.000Z',
    job_offer_expiration_timestamp: 1695945600,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Bachelor’s Degree in Computer Science or related field',
        'A minimum of 5 years of experience in software design and development',
        'Deep understanding of Computer Science fundamentals',
        'Strong development, debugging and troubleshooting skills',
        'Excellent written, verbal communication skills',
        'Able to work in teams and collaborative fashion',
        'React / React Native / Node.js using JavaScript / TypeScript',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Aquent',
    employer_logo:
      'https://masscapital.com/wp-content/uploads/2016/09/aquent-logo.png',
    employer_website: 'http://aquent.com',
    employer_company_type: 'Staffing',
    job_publisher: 'LinkedIn',
    job_id: '3WEd6rN7eFwAAAAAAAAAAA==',
    job_employment_type: 'FULLTIME',
    job_title: 'Front End React Developer',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/front-end-react-developer-at-aquent-3542402198',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5721,
    job_description:
      'Job Description:\n\nFront End Developer\n\nWe are seeking a Developer to join our team and help us develop digital tools and applications. As a Front-End Developer, you will be responsible for developing front end website architecture, building engaging and visually complex user interfaces, developing, testing, and improving UI on all web applications and client websites, assisting the development team with back-end website applications, ensuring cross-platform optimization, and ensuring the responsiveness of applications.\n\nResponsibilities\n• Develop front end website architecture\n• Build engaging as well as visually complex user interfaces\n• Develop, test, and improve UI on all web applications and client websites\n• Assist the development team with back-end website applications\n• Ensure cross-platform optimization\n• Ensure responsiveness of applications\n• Help QA test all web applications and assist in issue resolution\n• Work alongside graphic designers and art directors for web design features\n• See projects from conception to finished product\n• Design and develop APIs\n• Edit and support existing applications and digital tools\n• Manage our relationship with AWS and our managed hosting provider\n• Meet both technical and consumer needs\n• Stay abreast of best practices in UX and UI\n\nRequirements\n• Expertise with JavaScript, html, CSS\n• 5+ years of React web-application development experience\n• Expertise with Node\n• Experience with Hooks, Redux, Sagas, Cypress, & SCSS\n• Demonstrated experience with Git/GitHub\n• Strong proficiency in responsive design and development\n• Experience with AWS and associated services: Lambda, S3, CloudFront, API Gateway, Cognito, and Serverless environments\n• Familiarity with React Native would be ideal\n• Familiarity with database technology such as MySQL, Mongo DB and Mongoose\n• Excellent verbal communication skills\n• Good problem-solving skills\n• Attention to detail',
    job_is_remote: false,
    job_posted_at_timestamp: 1680129125,
    job_posted_at_datetime_utc: '2023-03-29T22:32:05.000Z',
    job_city: 'Austin',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=3WEd6rN7eFwAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-04-28T22:32:05.000Z',
    job_offer_expiration_timestamp: 1682721125,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Expertise with JavaScript, html, CSS',
        '5+ years of React web-application development experience',
        'Expertise with Node',
        'Experience with Hooks, Redux, Sagas, Cypress, & SCSS',
        'Demonstrated experience with Git/GitHub',
        'Strong proficiency in responsive design and development',
        'Experience with AWS and associated services: Lambda, S3, CloudFront, API Gateway, Cognito, and Serverless environments',
        'Familiarity with React Native would be ideal',
        'Familiarity with database technology such as MySQL, Mongo DB and Mongoose',
        'Excellent verbal communication skills',
        'Good problem-solving skills',
        'Attention to detail',
      ],
      Responsibilities: [
        'As a Front-End Developer, you will be responsible for developing front end website architecture, building engaging and visually complex user interfaces, developing, testing, and improving UI on all web applications and client websites, assisting the development team with back-end website applications, ensuring cross-platform optimization, and ensuring the responsiveness of applications',
        'Help QA test all web applications and assist in issue resolution',
        'Work alongside graphic designers and art directors for web design features',
        'See projects from conception to finished product',
        'Design and develop APIs',
        'Edit and support existing applications and digital tools',
        'Manage our relationship with AWS and our managed hosting provider',
        'Meet both technical and consumer needs',
        'Stay abreast of best practices in UX and UI',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Donato Technologies, Inc.',
    employer_logo:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcgsel4g8IpJ6Qo4NBNTyaOOftw2wjXCi9oOIM&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_id: '_syHhsA7zPMAAAAAAAAAAA==',
    job_employment_type: 'CONTRACTOR',
    job_title: 'C# Developer with React Native',
    job_apply_link:
      'https://www.linkedin.com/jobs/view/c%23-developer-with-react-native-at-donato-technologies-inc-3550758331',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5715,
    job_description:
      'Position: C# Developer with React Native\n\nLocation: Spring/TX (Day 1 Onsite)\n\nClient : HP\n\nExperience: 9+ years\n• 9+ years of hands-on experience in Windows application development with C#, and React Native technologies\n• Hands on experience in UWP application development, SDK implementation, design patterns, IPC, Thread Programming, dependency injection, Rest APIs, Dll boundaries etc.\n• Strong analytical and debugging skills\n• Good knowledge on Windows Programming - registry, certificates, file and folder security, WMI, Thread, sockets and system programming.\n• Knowledge of protobufs library, telemetry, WMI etc.\n• Familiarity with redux-saga architecture and writing unit test cases.\n• Knowledge on developing Hardware enabling Windows applications for Laptop and Desktop domain\n• Strong knowledge of libraries and frameworks\n• Knowledge on Agile methodologies\n• Good communication skills to interact with global teams',
    job_is_remote: false,
    job_posted_at_timestamp: 1680276807,
    job_posted_at_datetime_utc: '2023-03-31T15:33:27.000Z',
    job_city: 'Valley Spring',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 30.858892,
    job_longitude: -98.81781,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=_syHhsA7zPMAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-09-27T15:33:28.000Z',
    job_offer_expiration_timestamp: 1695828808,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 108,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        '9+ years of hands-on experience in Windows application development with C#, and React Native technologies',
        'Hands on experience in UWP application development, SDK implementation, design patterns, IPC, Thread Programming, dependency injection, Rest APIs, Dll boundaries etc',
        'Strong analytical and debugging skills',
        'Good knowledge on Windows Programming - registry, certificates, file and folder security, WMI, Thread, sockets and system programming',
        'Knowledge of protobufs library, telemetry, WMI etc',
        'Familiarity with redux-saga architecture and writing unit test cases',
        'Knowledge on developing Hardware enabling Windows applications for Laptop and Desktop domain',
        'Strong knowledge of libraries and frameworks',
        'Knowledge on Agile methodologies',
        'Good communication skills to interact with global teams',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113200',
    job_onet_job_zone: '4',
  },
  {
    employer_name: 'iAiSystem LLC',
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'ZipRecruiter',
    job_id: 'AJ6EgJEBgBoAAAAAAAAAAA==',
    job_employment_type: 'FULLTIME',
    job_title: 'React JS Developer',
    job_apply_link:
      'https://www.ziprecruiter.com/c/iAiSystem-LLC/Job/React-JS-Developer/-in-Dallas,TX?jid=c3843c293ac0b17f',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6685,
    job_description:
      'RESPONSIBILITIES:\n• Participate with the team to perform analysis, assessment, and resolution for defects and incidents of intermediate complexity and escalate appropriately.\n• Work within guidelines set by the team to independently tackle well-scoped problems.\n• 3+ years of experience with React.js\n• Thorough understanding of React.js and its core principles\n• Experience with popular React.js workflows (such as Flux or Redux)\n• Experience with RESTful APIs\n• Experience with Node.js\n• Knowledge of Mongo DB will be an added advantage\n• Experience with charting and mapping libraries is a plus\n• Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model\n• Knowledge of modern authorization mechanisms, such as JSON Web Token\n• Familiarity with modern front-end build pipelines and tools\n• Ability to understand business requirements and translate them into technical requirements\n• Good communication skills & good team player\n• Strong analytical skills for effective problem-solving.\n• Able to adapt to new platforms and constantly hone skills.\nLocation- WFH,3+ years,Full Time / Permanent',
    job_is_remote: false,
    job_posted_at_timestamp: 1635426941,
    job_posted_at_datetime_utc: '2021-10-28T13:15:41.000Z',
    job_city: 'Dallas',
    job_state: 'TX',
    job_country: 'US',
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=AJ6EgJEBgBoAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-04-30T00:00:00.000Z',
    job_offer_expiration_timestamp: 1682812800,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Experience with Node.js',
        'Knowledge of Mongo DB will be an added advantage',
        'Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model',
        'Knowledge of modern authorization mechanisms, such as JSON Web Token',
        'Ability to understand business requirements and translate them into technical requirements',
        'Good communication skills & good team player',
        'Strong analytical skills for effective problem-solving',
        'Able to adapt to new platforms and constantly hone skills',
      ],
      Responsibilities: [
        'Participate with the team to perform analysis, assessment, and resolution for defects and incidents of intermediate complexity and escalate appropriately',
        'Work within guidelines set by the team to independently tackle well-scoped problems',
        'Thorough understanding of React.js and its core principles',
        'Experience with popular React.js workflows (such as Flux or Redux)',
        'Experience with RESTful APIs',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
];
